module.exports = [
    { dish: "MAKARONFLAJŠ", title: "testenine", factor: 0.09, unit: "kg" },
    { dish: "MAKARONFLAJŠ", title: "mesni ragu", factor: 0.075, unit: "kg" },
    { dish: "TESTENINE S TUNO", title: "testenine", factor: 0.09, unit: "kg" },
    { dish: "TESTENINE S TUNO", title: "tuna", factor: 0.03, unit: "kg" },
    { dish: "TESTENINE S TUNO", title: "kisla smetana", factor: 0.05, unit: "kg" },
    { dish: "TORTELINI S SMETANOVO OMAKO", title: "tortelini", factor: 0.2, unit: "kg" },
    { dish: "TORTELINI S SMETANOVO OMAKO", title: "kisla smetana", factor: 0.03, unit: "kg" },
    { dish: "TORTELINI S SMETANOVO OMAKO", title: "topljeni sirček", factor: 1, unit: "kos" },
    { dish: "MESNA RIŽOTA", title: "riž", factor: 0.1, unit: "kg" },
    { dish: "MESNA RIŽOTA", title: "meso", factor: 0.3, unit: "kg" },
    { dish: "MESNA RIŽOTA", title: "grah", factor: 0.015, unit: "kg" },
    { dish: "MESNA RIŽOTA", title: "koruza", factor: 0.015, unit: "kg" },
    { dish: "MESNA RIŽOTA", title: "korenček", factor: 0.015, unit: "kg" },
    { dish: "ZELENJAVNA RIŽOTA", title: "riž", factor: 0.1, unit: "kg" },
    { dish: "ZELENJAVNA RIŽOTA", title: "grah", factor: 0.015, unit: "kg" },
    { dish: "ZELENJAVNA RIŽOTA", title: "koruza", factor: 0.015, unit: "kg" },
    { dish: "ZELENJAVNA RIŽOTA", title: "korenje", factor: 0.015, unit: "kg" },
    { dish: "ZELENJAVNA RIŽOTA", title: "bučke", factor: 0.015, unit: "kg" },
    { dish: "MLEČNI RIŽ", title: "riž", factor: 0.095, unit: "kg" },
    { dish: "MLEČNI RIŽ", title: "mleko", factor: 0.3, unit: "l" },
    { dish: "MLEČNI RIŽ", title: "voda", factor: 0.17, unit: "l" },
    { dish: "GRES", title: "pšenični zdrob", factor: 0.05, unit: "kg" },
    { dish: "GRES", title: "mleko", factor: 0.2, unit: "l" },
    { dish: "GRES", title: "voda", factor: 0.2, unit: "l" },
    { dish: "GRES", title: "kakav", factor: 0.018, unit: "kg" },
    { dish: "PEČENI PURANJI ZREZKI S PRILOGO", title: "zrezki", factor: 0.11, unit: "kg" },
    { dish: "PEČENI PURANJI ZREZKI S PRILOGO", title: "krompir", factor: 0.35, unit: "kg" },
    { dish: "PEČENI PURANJI ZREZKI S PRILOGO", title: "rdeča pesa", factor: 0.1, unit: "kozarec" },
    { dish: "PEČENI PURANJI ZREZKI S PRILOGO", title: "kumare", factor: 0.1, unit: "kg" },
];