module.exports = [
    { title: "slanina", factor: 0.020, unit: "kg" },
    { title: "sol", factor: 0.0005, unit: "kg" },
    { title: "sliva", factor: 3, unit: "kos" },
    { title: "sladkor", factor: 0.006, unit: "kg" },
    { title: "sladka smetana", factor: 0.1, unit: "l" },
    { title: "sir", factor: 0.030, unit: "kg" },
    { title: "suha salama", factor: 0.020, unit: "kg" },
    { title: "sladoled", factor: 0.100, unit: "kg" },
    { title: "sirni namaz", factor: 0.015, unit: "kg" },
    { title: "skuta", factor: 0.050, unit: "kg" },
    { title: "stročji fižol", factor: 0.250, unit: "kg" },
    { title: "slive (sveže)", factor: 3, unit: "kos" },
    { title: "slive (posušene)", factor: 5, unit: "kos" },
    { title: "sojino mleko", factor: 0.1, unit: "l" },
    { title: "sardine v konzervi", factor: 0.060, unit: "kg" },
    { title: "skuše v konzervi", factor: 0.060, unit: "kg" },
    { title: "sončnična semena", factor: 0.050, unit: "kg" },
    { title: "sadni sirup za redčenje", factor: 0.003, unit: "l" },
    { title: "sok", factor: 0.2, unit: "l" },
    { title: "šparglji", factor: 0.125, unit: "kg" },
    { title: "špinača", factor: 0.150, unit: "kg" },
    { title: "špageti", factor: 0.100, unit: "kg" },
    { title: "šunka", factor: 0.020, unit: "kg" },
    { title: "testenine", factor: 0.125, unit: "kg" },
    { title: "tuna v konzervi", factor: 0.060, unit: "kg" },
    { title: "teletina", factor: 0.080, unit: "kg" },
    { title: "toast", factor: 4, unit: "kos" },
    { title: "vanilin sladkor", factor: 0.004, unit: "kg" },
    { title: "višnje", factor: 0.150, unit: "kg" },
    { title: "zelena solata", factor: 0.2, unit: "glava" },
    { title: "zelena ", factor: 0.1, unit: "glava" },
    { title: "zelje", factor: 0.2, unit: "glava" },
    { title: "zaseka", factor: 0.010, unit: "kg" },
    { title: "zdrob", factor: 0.080, unit: "kg" },
    { title: "žemlja", factor: 1, unit: "kos" },
];